# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: root1234
  CLOUD_SQL_DATABASE_NAME: soccerhoursdb
  CLOUD_SQL_CONNECTION_NAME: footyhours:us-central1:footydb
# [END gae_python37_cloudsql_config]
